[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && gunicorn --bind 0.0.0.0:$PORT main:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"

